import type { Metadata } from "next";
import { Figtree } from "next/font/google";
import ChatbotFab from "@/components/chatbot-fab";
import "./globals.css";
import Providers from "@/app/providers";
import Script from "next/script";

const figtree = Figtree({
  variable: "--font-figtree",
  subsets: ["latin"],
});

export const dynamic = 'force-dynamic'
export const metadata: Metadata = {
  title: "Guide Michelin",
  description: "Generated by create next app",
  icons: {
    icon: "/star.svg",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="fr"
      className={`${figtree.variable} h-full antialiased`}
    >
      <head>
        <link
          rel="stylesheet"
          href="https://unpkg.com/leaflet@1.9.4/dist/leaflet.css"
        />
        <Script
          src="https://unpkg.com/leaflet@1.9.4/dist/leaflet.js"
          strategy="beforeInteractive"
        />
      </head>
      <body className={`${figtree.className} min-h-full flex flex-col`}>
      <Providers>
        {children}
        <ChatbotFab />
      </Providers>
      </body>
    </html>
  );
}
