import type { Metadata } from "next";
import { Figtree } from "next/font/google";
import ChatbotFab from "@/components/chatbot-fab";
import "./globals.css";
import Providers from "@/app/providers";

const figtree = Figtree({
  variable: "--font-figtree",
  subsets: ["latin"],
});


export const metadata: Metadata = {
  title: "Guide Michelin",
  description: "Generated by create next app",
  icons: {
    icon: "/star.svg",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="fr"
      className={`${figtree.variable} h-full antialiased`}
    >
      <body className={`${figtree.className} min-h-full flex flex-col`}>
      <Providers>
        {children}
        <ChatbotFab />
      </Providers>
      </body>
    </html>
  );
}
